syntax on
set bg=dark
inoremap kj <Esc>
inoremap jk <Esc>
cnoremap kj <Esc> 
cnoremap jk <Esc> 
vnoremap kj <Esc>
vnoremap jk <Esc>

set number 
set noswapfile
set t_Co=256

" bootstrap plugins
call plug#begin('~/.vim/plugged') 
Plug 'morhetz/gruvbox' 
Plug 'Shougo/vimfiler.vim'
Plug 'Shougo/unite.vim'
Plug 'tpope/vim-fugitive'
Plug 'jonmorehouse/vim-flow'
call plug#end()

colorscheme gruvbox 

let g:vimfiler_enable_auto_cd=1
let g:vimfiler_as_default_explorer=1
let g:vimfiler_safe_mode_by_default=0
let g:vimfiler_ignore_pattern=0
let g:vimfiler_force_overwrite_statusline=1

" make sure vimfiler windows work correctly with vim-fugitive
autocmd Filetype vimfiler call fugitive#detect(getcwd())
map E :VimFiler<CR>
let g:vimfiler_execute_file_list = {}
let g:vimfiler_execute_file_list['_'] = 'vim'

let mapleader = ","
map <Leader>v :execute("vsplit")<CR>
map <Leader>s :execute("split")<CR>
map <Leader>u :execute("only")<CR>
map <Leader>c :execute("close")<CR>
 
map <Leader>j :wincmd j<CR>
map <Leader>h :wincmd h<CR>
map <Leader>k :wincmd k<CR>
map <Leader>, :FlowRun<CR>

map mm :VimFiler<cr>
map mq :q<cr>
map s :wall<cr>
