---
default:
        cmd: | #!/usr/bin/env bash


                clear
                cd ~/code/interview_practice/max_bst

                go build  -o /tmp/interview_practice/max_bst .
                /tmp/interview_practice/max_bst
