---
default:
        cmd: | #!/usr/bin/env bash


                clear
                cd ~/code/std

                go build  commands.go functions.go listStructure.go main.go .
                /tmp/std
